local_backend: true
backend:
  name: git
  repo: "WesleyFalize/Blog" # GitHub repo in username/repo format
  branch: main


media_folder: "static/images/uploads" # Folder for images
public_folder: "/images/uploads"      # Public path for images

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Author", name: "author", widget: "list", default: ["Wesley Falize"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", default: "" }
      - { label: "Summary", name: "summary", widget: "string", default: "" }
      - { label: "Tags", name: "tags", widget: "list", default: ["Hugo", "Blog"] }
      - { label: "Categories", name: "categories", widget: "list", default: ["Blog"] }
      - { label: "Series", name: "series", widget: "list", default: ["Getting started with a blog"] }
      - { label: "Show Table of Contents", name: "ShowToc", widget: "boolean", default: true }
      - { label: "Table of Contents Open", name: "TocOpen", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
