backend:
  name: git
  repo: "WesleyFalize/Blog" # GitHub repo in username/repo format
  branch: main

media_folder: "static/images/uploads" # Folder for images
public_folder: "/images/uploads"      # Public path for images

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
